"""Added completion cols to tasks

Revision ID: aa6d9ee3c6cd
Revises: 3bdc2b35f3c8
Create Date: 2025-10-17 01:11:17.623614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa6d9ee3c6cd'
down_revision = '3bdc2b35f3c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_on', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('completed_on', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('is_completed', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('is_completed')
        batch_op.drop_column('completed_on')
        batch_op.drop_column('created_on')

    # ### end Alembic commands ###
